inventario:
    resource: "@InventarioBundle/Resources/config/routing.yml"
    prefix:   /

seminario:
    resource: "@SeminarioBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

logout:
    path:   /logout

login_route:
    path:     /login
    defaults: { _controller: SeminarioBundle:Security:login }
login_check:
    path: /login_check