security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
            #algorithm: bcrypt
            #cost: 12



    providers:
        in_memory:
            memory:
                users:
                    hugo:  { password: hug , roles: [ 'ROLE_USER' ] }
                    admin: { password: hugo , roles: [ 'ROLE_ADMIN' ] }

    firewalls:

        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            #stateless:  false
            logout:
                path:   /evento/evento_logout
                target: /seminario
                  #delete_cookies:
                   # admin: { path: /evento, domain: null }


    access_control:
       # - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
      # - { path: ^/evento, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/evento, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


