security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
            #algorithm: bcrypt
            #cost: 12


    role_hierarchy:
        ROLE_USUARIO: ROLE_USER
        ROLE_ADMIN: ROLE_USUARIO



    providers:
        in_memory:
            memory:
                users:
                    hugo:  { password: passxx , roles: [ 'ROLE_USUARIO' ] }
                    admin: { password: password , roles: [ 'ROLE_ADMIN' ] }

    firewalls:

        seminario:
            pattern:    ^/
            http_basic: ~
            logout:
                path:   /logout
                target: /evento

        secured_area:
            pattern:    ^/ #cualquier peticion entrante
            anonymous: ~ #acceso usuarios anonimos
            http_basic: ~
            #stateless:  false
            logout:
                path:   /logout
                target: /evento
               # invalidate_session: true

                  #delete_cookies:
                   # admin: { path: /evento, domain: null }


    access_control:
       # - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
      # - { path: ^/evento, roles: IS_AUTHENTICATED_ANONYMOUSLY }

       - { path: ^/seminario, roles: ROLE_ADMIN } #cualquier URL que coincida con la expresión /admin o /admin/*




