security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext




    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: hugol , roles: [ 'ROLE_ADMIN' ] }

    firewalls:

        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            logout:
                path:   /logout
                target: /seminario
                delete_cookies:
                    admin: { path: /evento, domain: null }


    access_control:
       # - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
       - { path: ^/evento, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


