responsable:
    path:     /
    defaults: { _controller: "SeminarioBundle:Responsable:index" }

responsable_show:
    path:     /{id}/show
    defaults: { _controller: "SeminarioBundle:Responsable:show" }

responsable_new:
    path:     /new
    defaults: { _controller: "SeminarioBundle:Responsable:new" }

responsable_create:
    path:     /create
    defaults: { _controller: "SeminarioBundle:Responsable:create" }
    requirements: { _method: post }

responsable_edit:
    path:     /{id}/edit
    defaults: { _controller: "SeminarioBundle:Responsable:edit" }

responsable_update:
    path:     /{id}/update
    defaults: { _controller: "SeminarioBundle:Responsable:update" }
    requirements: { _method: post|put }

responsable_delete:
    path:     /{id}/delete
    defaults: { _controller: "SeminarioBundle:Responsable:delete" }
    requirements: { _method: post|delete }
