seminario_aviso:
    resource: "@SeminarioBundle/Resources/config/routing/aviso.yml"
    prefix:   /aviso

seminario_evento:
    resource: "@SeminarioBundle/Resources/config/routing/evento.yml"
    prefix:   /evento

seminario_responsable:
    resource: "@SeminarioBundle/Resources/config/routing/responsable.yml"
    prefix:   /responsable

seminario_seminario:
        resource: "@SeminarioBundle/Resources/config/routing/seminario.yml"
        prefix:   /seminario


seminario_index:
    path:     /
    defaults: { _controller: "SeminarioBundle:Evento:index" }